### ISSUE TITLE
reverse proxy with nginx?

### ISSUE THREAD

**Issue by paOol** [DylanPiercey/auto-sni#10]
how would this work if you use nginx as a reverse proxy ?

what would the nginx configuration look like?

**Comment by DylanPiercey** [comment]
It would be the same as routing nginx to (with ssl) to any https server. Auto-SNI stores the certificates in `~/letsencrypt/etc/live/mydomain.com` so you should be able to have nginx point there.

Feel free to shoot me a message on gitter, or leave another message here, if you need any more help.
