### ISSUE TITLE
Usage without custom createServer

### ISSUE THREAD

**Issue by Rush** [DylanPiercey/auto-sni#11]
Like your idea but I have my own http server instance, could I use your module to only manage certificates? And preferably only a subset of them, the ones obtained through let's encrypt.

**Comment by DylanPiercey** [comment]
Do you think the docs from Restify will resolve your issue? Can you post some example code?

**Comment by DylanPiercey** [comment]
@rush I'm going to close this issue since I believe the restify section of the docs should be what you are looking for. Feel free to get back to me if this is not the case.
