### ISSUE TITLE
Keeps trying to create "static/" directory, fails.

### ISSUE THREAD

**Issue by Analogreality** [DylanPiercey/auto-sni#12]
I'm getting an error when I attempt to create the server with Express.
fs.js:651
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EEXIST, file already exists '../node_modules/auto-sni/static'
at Object.fs.mkdirSync (fs.js:651:18)

**Comment by DylanPiercey** [comment]
What node version and OS?

**Comment by Analogreality** [comment]
Debian and Node v0.10.29

**Comment by DylanPiercey** [comment]
Currently I'm only supporting 4.0+ but ill take a look later today to see if I can get things going.

**Comment by Analogreality** [comment]
Thanks, I appreciate it.

**Comment by DylanPiercey** [comment]
@Analogreality Sadly it seems like `0.10.x` doesn't support async SNICallbacks, making auto sni useless. I just released an update which fixes support for `0.11` and up though. If you think i've missed something please feel free to leave another comment, sorry I couldn't resolve this completely for you.
