### ISSUE TITLE
auto-sin with express seems to keep using staging server & self signed cert

### ISSUE THREAD

**Issue by GastonHummel** [DylanPiercey/auto-sni#13]
Even with the following settings I seem to keep getting the self-signed certificate from "Fake LE Intermediate X1"

createServer({
  email: "my.email@hotmail.com",
  agreeTos: true,
  debug: **false**,
  domains: ["enkarma.co.uk"],
  forceSSL: true,
  ports: {
    http: 80,
    https: 443
  }
}, app);

Is setting debug: false not sufficient?  Thanks in advance for your help.

**Comment by GastonHummel** [comment]
Deleting my "old" letsencrypt directory which in the accounts folder had a file pointing to the letsencrypt's staging server resolved the issue.  During my first test I had "debug:true" set in the createServer command.  Once you have run the command with "debug:true", changing it to "debug:false" does not cause the package to point to letsencypts' production server until you delete the old letsencrypt directory.

Thank you for creating and sharing this extremely useful and easy to use package! Much appreciated.

**Comment by DylanPiercey** [comment]
@GastonHummel thanks very much for creating this issue. I've known of this but keep forgetting to address it.

I'm going to try to address this (and another issue where bundle certs don't get updated unless the first domain in the bundle is different) today and if I can't i'll add a `known issues` section for the time being.

Sorry this one tripped you up.

**Comment by DylanPiercey** [comment]
@GastonHummel this should be resolved in `1.1.0`.

**Comment by GastonHummel** [comment]
Thanks very much for resolving Dylan!

Kind regards,

Gaston
