### ISSUE TITLE
Possible to work with aws elastic beanstalk?

### ISSUE THREAD

**Issue by cchitsiang** [DylanPiercey/auto-sni#14]
Probably a stupid question.

Any idea or steps to make this work under AWS elastic beanstalk environment?

**Comment by DylanPiercey** [comment]
@cchitsiang Not familiar with that environment, could you list the constraints you are facing?

**Comment by DylanPiercey** [comment]
@cchitsiang I think this is probably possible but is probably a question best to ask people (and myself) on gitter since it will require some back and forth.

I'm going to close this issue for now.
