### ISSUE TITLE
Location of certificates/static files

### ISSUE THREAD

**Issue by jus101** [DylanPiercey/auto-sni#15]
Hi,

I'm trying to use auto-sni inside of a docker container node app.
Problem is, any time I restart the container, new certificates are requested. After a few restarts, I soon hit the LE rate limits.

Looking at the source, I think the certificates and other files are stored in the module's 'static' directory. Is that correct? If so, would it be possible to pass in an option to specify another directory? That way I can run the container with a volume mounted so that the files in static are persisted across container restarts.

Any info appreciated.

Thanks

**Comment by DylanPiercey** [comment]
@jus101 'static' is used just to verify domain ownership with letsencrypt and is fine that it gets deleted every time. Certificates are stored in `~/letsencrypt/etc/live/:host/`. Does this help resolve your issue or do you still this an override for this is needed?

**Comment by jus101** [comment]
Ah OK - that's cool. I'll just mount volume to ~/letsencrypt/

Thanks!

**Comment by DylanPiercey** [comment]
@jus101 glad to help.
