### ISSUE TITLE
use fullchain.pem instead of cert.pem

### ISSUE THREAD

**Issue by jumoog** [DylanPiercey/auto-sni#17]
it looks like we using cert.pem as cert
but we have to use fullchain.pem to fix the "invalid CA issue"

**Comment by DylanPiercey** [comment]
@jumoog I thought I was? Unless I'm missing something?

https://github.com/DylanPiercey/auto-sni/blob/master/lib/load.js#L63

**Comment by jumoog** [comment]
It's a Node 6 issue

**Comment by jumoog** [comment]
using Node 5 fixed my issue
