### ISSUE TITLE
root access question

### ISSUE THREAD

**Issue by barbalex** [DylanPiercey/auto-sni#19]
In the readme you say to run the following command to give Node access to ports 80 and 443:

    sudo setcap cap_net_bind_service=+ep $(which node)

I am a linux noob so `node` does not mean anything go me.

Here come the questions:

- What is a node?
- how do I know which node I have to refer to?
- do the `$()` characters have to be written or is this a placeholder for the node name?

**Comment by DylanPiercey** [comment]
`which` is a command that returns the path to a executable, in this case node js. `which node` just returns where node js is.

`$()` says to bash "evaluate the contents between these parans. So basically the command calls `sudo setcap cap_net_bind_service=+ep` on wherever your node executable can be found. If you were using iojs for example you could also use `which iojs`.

Let me know if this is unclear, closing for now!

**Comment by barbalex** [comment]
Thanks a lot. And most of all: for this great tool!

Auf dem Handy geschrieben
Am 15.06.2016 5:29 nachm. schrieb "Dylan Piercey" <notifications@github.com
