### ISSUE TITLE
mention dependencies on windows in the readme

### ISSUE THREAD

**Issue by barbalex** [DylanPiercey/auto-sni#20]
Auto-sni uses ursa (https://github.com/quartzjer/ursa). 

When Installing on windows I got this error message:

    C:\Users\alex\ae_api\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
     else (node "" rebuild )
    Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
      ursaNative.cc
    ..\src\ursaNative.cc(157): warning C4244: 'argument' : conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(172): warning C4244: 'argument' : conversion from 'ssize_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(378): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(379): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(686): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(734): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(779): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(826): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(945): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    ..\src\ursaNative.cc(1003): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
      win_delay_load_hook.c
    LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\alex\ae_api\node_modules\ursa\build\ursaNative.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
    gyp ERR! stack     at emitTwo (events.js:106:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    gyp ERR! System Windows_NT 10.0.10586
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\alex\ae_api\node_modules\ursa
    gyp ERR! node -v v6.2.1
    gyp ERR! node-gyp -v v3.3.1
    gyp ERR! not ok
    npm WARN install:ursa@0.9.4 ursa@0.9.4 install: `node-gyp rebuild`
    npm WARN install:ursa@0.9.4 Exit status 1
    ae_api@0.0.1 C:\Users\alex\ae_api
    `-- auto-sni@1.1.3  extraneous

When checking ursa I found this information in their readme: https://github.com/quartzjer/ursa#windows-install.

So on Windows, you need to install some dependencies first.

It would be helpful for the next windows users to find this information in auto-sni's readme before trying to install auto-sni.

**Comment by DylanPiercey** [comment]
If any one could verify these dependencies and add them to the readme that would be great. Currently it is my understanding that auto-sni does not work on windows and does not have official support.

**Comment by DylanPiercey** [comment]
Going to close this since windows is not officially supported, but I would accept a PR if this is still an issue.
