### ISSUE TITLE
new version of letsencrypt v1.5.0

### ISSUE THREAD

**Issue by coolaj86** [DylanPiercey/auto-sni#23]
Just a heads up:

I just published a new version of letsencrypt - v1.5.0

(also a new version of letiny-core v2.0.0 and a new dependency rsa-compat - all to fix various bugs)

There shouldn't be any breaking changes to the API, but it does require a shim for the new Buffer methods that aren't implemented in older version of node.

Let me know if you have any problems or if I can answer any questions.

**Comment by DylanPiercey** [comment]
@coolaj86 thanks for the headsup. What version of node does the module require now?

**Comment by coolaj86** [comment]
I included `buffer-v6-polyfill`, so it should work in everything that the old one worked in. The only breaking change was removing some deprecated uses of `new Buffer()`

**Comment by DylanPiercey** [comment]
Awesome thanks. Released in https://github.com/DylanPiercey/auto-sni/commit/5b4635069d39f94492a20d6ecec1648eb8a25bfd.

**Comment by coolaj86** [comment]
As another heads up I got on a roll and started fixing a bunch of bugs and adding requested features. 

The result will soon be available as v2.0.0, but the docs are available now:

https://github.com/Daplie/node-letsencrypt/tree/v2.x

I'm still in the process of stripping it down and testing before publishing, but it's already much, much simpler.

**Comment by coolaj86** [comment]
Okay v2 is out: https://github.com/Daplie/node-letsencrypt

* Smaller code base
* More thoroughly tested
* Hooks for saving to sql, mongo, etc (plugin architecture for storage)
* All bugs squashed (at least I'm pretty sure)
* Supports multiple altnames
* Better windows support (fixed filepath issues in `le-store-certbot`)

You can see the new API examples in the README and in the tests:
https://github.com/Daplie/node-letsencrypt/tree/master/tests
