### ISSUE TITLE
SSL peer handshake fails, how to reset?

### ISSUE THREAD

**Issue by rcpeters** [DylanPiercey/auto-sni#26]
Everything was working dandy and I was optimizing how to config our app. Something when wrong and I no longer get error messages.

This is what curl returns

        curl -kv https://localhost:8443
        * Rebuilt URL to: https://localhost:8443/
        *   Trying ::1...
        * Connected to localhost (::1) port 8443 (#0)
        * SSL peer handshake failed, the server most likely requires a client certificate to connect
        * Closing connection 0
        curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

my current config:

        secureServer = createServer({
          email: config.LETSENCRYPT_ISSUES_EMAIL, // Emailed when certificates expire.
          agreeTos: true, // Required for letsencrypt.
          debug: true, // Add console messages and uses staging LetsEncrypt server. (Disable in production)
          domains: [["localhost","www.localhost"]], // List of accepted domain names. (You can use nested arrays to register bundles with LE).
          forceSSL: true, // Make this false to disable auto http->https redirects (default true).
          redirectCode: 301, // If forceSSL is true, decide if redirect should be 301 (permanent) or 302 (temporary). Defaults to 302
          ports: {
            http: 8080, // Optionally override the default http port.
            https: 8443 // Optionally override the default https port.
          }
        }, app);

No errors on the console. How do I see what the error is?

**Comment by jefftham** [comment]
Please bear in mind that letsencrypt is not allow to issue cert for localhost. You need to include your domain.  
[reference](https://community.letsencrypt.org/t/can-i-test-lets-encrypt-client-on-localhost/15627)

**Comment by rcpeters** [comment]
Yes, but auto-sni should fall back to a self signed cert and but now my app is stuck in this state for local dev.

**Comment by jefftham** [comment]
if you want to generate a self signed cert, you should provide a legitimate domain name and set the debug to true.

**Comment by DylanPiercey** [comment]
You can always manually remove the ~/letsencrypt folder to regenerate certificates. Is that what you are looking for?

**Comment by rcpeters** [comment]
Bing! 🎉 🌮 Sorry I assumed that would be under the node_modules.

**Comment by DylanPiercey** [comment]
@rcpeters glad to hear that solves you problems. I'll be sure to add this to the docs once I get a second. 👍
