### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by mwaschkowski** [DylanPiercey/auto-sni#30]
Hi,

I'm running auto-sni on my node.js server in ubuntu on a digital ocean vps with the code below. It works fine for http, but when going to https I get a certificate error shown here:

Certificate Error
There are issues with the site's certificate chain (net::ERR_CERT_AUTHORITY_INVALID).

![image](https://cloud.githubusercontent.com/assets/1027250/21657401/0ebfcd96-d290-11e6-84d4-982a35f94ec8.png)

I'm not sure what's wrong...

Thank you,

Mark

`var createServer = require("auto-sni");
var express      = require("express");
var app          = express();

app.get("/test", function (req, res) {
    res.end('Hello, World!123');
  });

createServer({ 
    email: "mark@appweaverz.com",
    server: 'https://acme-v01.api.letsencrypt.org/directory',
    agreeTos: true,    
    debug: true, // Add console messages and uses staging LetsEncrypt server. (Disable in production)
    domains: ["traqify.com"], // List of accepted domain names. (You can use nested arrays to register bundles with LE).
    forceSSL: false, // Make this false to disable auto http->https redirects (default true).
    redirectCode: 301, // If forceSSL is true, decide if redirect should be 301 (permanent) or 302 (temporary). Defaults to 302
    ports: {
        http: 80, // Optionally override the default http port.
        https: 443 // Optionally override the default https port.
    } }, app);
`

**Comment by DylanPiercey** [comment]
This is because of the debug option (uses let's encrypt dev servers for testing). Set debug to false and this should be resolved.

**Comment by jefftham** [comment]
@DylanPiercey,  I suggest to use the debug option to switch value of the "server".  Just get rid of the server option from the object, and hard coded it in the script. Change the value base on the value of "debug". How do you think?
