### ISSUE TITLE
renewal

### ISSUE THREAD

**Issue by mwaschkowski** [DylanPiercey/auto-sni#36]
Hi,

I've received emails saying that my cert is going to expire, I thought this was supposed to auto-renew? I searched for 'renewal' on this Git site but didn't get any results. Can you give me some guidance on looking into this further, unsure of what to do...

Thank you!

Mark

**Comment by DylanPiercey** [comment]
That's an email from let's encrypt. It will auto renew but the email is something I cannot disable :p. It's also good to keep to know when it's getting renewed in case there is some unexpected issue with renewal.

**Comment by mwaschkowski** [comment]
Hi Dylan,

OK great, thanks for the clarification. I just received yesterday:

Hello,

>
> Your certificate (or certificates) for the names listed below will expire
> in
> 9 days (on 05 Apr 17 14:06 +0000). Please make sure to renew
> your certificate before then, or visitors to your website will encounter
> errors.
> traqify.com
> For any questions or support, please visit https://community.letsencrypt.
> org/.
> Unfortunately, we can't provide support by email.
> For details about when we send these emails, please visit
> https://letsencrypt.org/docs/expiration-emails/. In particular, note
> that this reminder email is still sent if you've obtained a slightly
> different certificate by adding or removing names. If you've replaced
> this certificate with a newer one that covers more or fewer names than
> the list above, you may be able to ignore this message.
> If you want to stop receiving all email from this address, click
> http://mandrillapp.com/track/unsub.php?u=30850198&id=
> fc909961664e4bce83c35531213fef32.iXxPWcIbxZOcoqdm6KLCnDLHOIE%
> 3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Dmark%
> 2540appweaverz.com
> (Warning: this is a one-click action that cannot be undone)
> Regards,
> The Let's Encrypt Team


Shouldn't this have renewed already?

Thanks again,

Mark

**Comment by DylanPiercey** [comment]
You can double check in your browser. If you click on the green lock (chrome or safari) it should say when the certificate was created.

**Comment by mwaschkowski** [comment]
Hi Dylan,

OK, thanks a lot, I was able to verify that its been renewed:

[image: Inline image 1]

Chrome only shows you through the developer tools now (under the security
tab) can't click on the icon any more (used to be able to but not since
v55). I'll ignore the emails.

Thanks again!

Mark

**Comment by DylanPiercey** [comment]
No problem glad to help. I personally use the emails as a reminder to double check that the cert was renewed.
