### ISSUE TITLE
letsencrypt has been renamed to greenlock

### ISSUE THREAD

**Issue by janwo** [DylanPiercey/auto-sni#37]
When I install the module, I get the following warning: `letsencrypt@1.5.1: letsencrypt has been renamed to greenlock. Please find it at npm greenlock`

Any plans to update this?

**Comment by DylanPiercey** [comment]
The API has completely changed and would likely require a rewrite of this module to integrate. I will dig about draper when I get some time.

**Comment by DylanPiercey** [comment]
@janwo I have updated auto-sni to use 'greenlock-express'. There were some features removed (disabling forcessl and custom redirect https status code) but the api is more/less the same (except for  restify users.)

This module is now an extremely thin wrapper and is only 51 loc. Please try updating and let me know how this goes!

**Comment by janwo** [comment]
@DylanPiercey I tried it out now, but now it does not work on my hapi environment anymore. Any ideas?

`le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
[le/lib/middleware.js] created middleware
Handling ACME challenges and redirecting to https on plain port 80
Handling ACME challenges and serving https 443
`
And thats it...

**Comment by DylanPiercey** [comment]
@janwo can you post your setup code?

**Comment by janwo** [comment]
```
// Load SSL key and certificate.
let autoSni = AutoSNI({
    email: Config.backend.mails.admin,
    agreeTos: true,
    debug: Config.debug,
    domains: [
	Config.backend.domain
    ],
    ports: {
	http: Config.backend.ports.http,
	https: Config.backend.ports.https
    }
});

// Create server connection.
server.connection({
	listener: autoSni,
	tls: true,
	autoListen: false
});
```

I removed `forceSSL` and the redirectCode in order to stay compatible to your update.

**Comment by DylanPiercey** [comment]
And you are running this on a server that is being accessed by `Config.backend.domain`?

**Comment by janwo** [comment]
Oh, I think I solved the error. I used the `https` prefix within the config. I try that out now. Sorry for wasting your time 🙄

**Comment by DylanPiercey** [comment]
No problems happy to help.

**Comment by janwo** [comment]
@DylanPiercey I changed the domain back to `placeholder.com` and I experience the same behaviour as mentioned above. 😞
