### ISSUE TITLE
error in 2.1.1 : le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb)

### ISSUE THREAD

**Issue by jefftham** [DylanPiercey/auto-sni#38]
version 2.1.1 throws error as:
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed

However, version 1.5.1 working fine.

using: nodejs, npm, express as:

    let server = createServer({
      email: 'xxx@abc.com',
      agreeTos: true,
      debug: false,
      domains: [ ['abc.com', 'www.abc.com'] ], // i use nested array
      ports: {
        http: 8080, 
        https:8443 
      }
    }, app);

**Comment by DylanPiercey** [comment]
Hey @jefftham, with @2.x of this library it has been completely changed to be an extremely thin wrapper around greenlock-express.

When I first created this module Greenlock (at the time node-letsencrypt) had a very unfriendly api and was missing many features. However now most of these features have been and so I have mostly stopped my efforts and changed this library to wrap their updated api.

The bundled domains option is currently missing from greenlock-express but with @2.2 I have made it so that the domain option is automatically flattened so that your existing config will still atleat work (it will not bundle though).

**Comment by jefftham** [comment]
@DylanPiercey , i just tried the v2.2.1, the error still occur.
it is not the error cause by the nested domains.

it shows 
`le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed`

**Comment by DylanPiercey** [comment]
@jefftham can you try removing and reinstalling your node modules? I can't seem to recreate this.

**Comment by jefftham** [comment]
I created a new vm and try.
It did generate a cert if I set debug=true.
However, error occurs if debug=false.

**Comment by DylanPiercey** [comment]
@jefftham what if you use ports http:80 and https:443? I'm curious if its a port issue.

**Comment by jefftham** [comment]
Yes,  I use 80 and 443.

**Comment by DylanPiercey** [comment]
@jefftham can you run the standard (manual) lets encrypt client? Are those ports actually open? I'm a little stumped.

**Comment by jefftham** [comment]
I think it is caused by greenlock-express.

i tested their QuickStart guide, it gives me the same error.


`'use strict'; 
require('greenlock-express').create({ 
  server: 'https://acme-v01.api.letsencrypt.org/directory' 
, email: 'xxx@example.com' 
, agreeTos: true 
, approveDomains: [ 'xxx.example.com' ] 
, app: require('express')().use('/', function (req, res) {
    res.end('Hello, World!');
  }) 
}).listen(80, 443);`

error message:-
`le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Handling ACME challenges and redirecting to https on plain port 80
Handling ACME challenges and serving https 443`


Maybe you should consider to change the library to [letsencrypt-express](https://www.npmjs.com/package/letsencrypt-express) from greenlock-express

**Comment by jefftham** [comment]
[Ticket from greenlock-express](https://git.daplie.com/Daplie/greenlock-express/issues/127)

**Comment by DylanPiercey** [comment]
@jefftham thanks for checking that out. I may consider switching from greenock-express in the future but for now I will close this issue and we can follow the progress on the greenlock repo.
