### ISSUE TITLE
Challenge route?

### ISSUE THREAD

**Issue by janwo** [DylanPiercey/auto-sni#40]
Hey Dylan,

my certificates are not getting updated. Am I right that since the big update, there is no well-known endpoint anymore?

**Comment by DylanPiercey** [comment]
The 'big update' essentially just pushed most of the work of this module off to greenlock-express while maintaining the same API. Originally when I made this module node-letsencrypt was extremely tedious to use but they have now more or less fixed it.

The module seems to be still working for me though. Can you post your config?

**Comment by janwo** [comment]
````js   
    let autoSni = AutoSNI({
	   email: Config.backend.mails.admin,
	   agreeTos: true,
	   debug: Config.debug,
	   domains: [ [ 'example.com', 'www.example.com' ] ],
	   ports: {
	      http: 80,
              https: 443
	   }
    });

    // Create server connection.
    server.connection({
	listener: autoSni,
	tls: true,
	autoListen: false
    });
`````
That's my config. I can ping 443 and 80. But I get 

````js
{
 type: 'urn:acme:error:rateLimited',
 detail: 'Error creating new authz :: Too many invalid authorizations recently.', 
 status: 429 
}

**Comment by janwo** [comment]
I am using the API of `greenlock-express` now. However, it works using approveDomains as callback function.

**Comment by DylanPiercey** [comment]
@janwo awesome thanks for letting me know the solution. Perhaps I'll add the ability to provide a function here as well.
