### ISSUE TITLE
FYI: new version of node-letsencrypt

### ISSUE THREAD

**Issue by coolaj86** [DylanPiercey/auto-sni#5]
Hey Dylan, I just wanted to make you aware that I published a new version of `letsencrypt` (v1.0.8). It fixes a bug where the `registerAsync` would return before registration was complete and a bug in the pyconf parser/stringifier.

I don't think anything should have broken, but please let me know if you have any issues with it.

**Comment by DylanPiercey** [comment]
@coolaj86 Thanks for letting me know!

I'll run it to some tests and make an update.

**Comment by DylanPiercey** [comment]
@coolaj86 Looks like current version is 1.4.2 which I updated to yesterday, is there another release that I am missing?

**Comment by DylanPiercey** [comment]
Closing this for now, @coolaj86 let me know if I've missed something.

**Comment by coolaj86** [comment]
I had my versions confused. I was referencing `letsencrypt-express` (similar to what you have here, but with a callback for initial approval). That said, I did publish a new version of `letsencrypt` just now with a few bugfixes.

**Comment by DylanPiercey** [comment]
Cool thanks, i'll take a look later today.

**Comment by DylanPiercey** [comment]
Looks good to me. Good work @coolaj86 and @martinheidegger. Updated deps in https://github.com/DylanPiercey/auto-sni/commit/db07d76ab4f0e7309cc5ee600375c6707ed38c12.
