### ISSUE TITLE
Creating certificate fails on Windows.

### ISSUE THREAD

**Issue by brighthero** [DylanPiercey/auto-sni#7]
This is the error I get:
```
D:\SOMEPROJECT\node_modules\auto-sni\lib\index.js:54
    .once('close', httpServer.close.bind(httpServer))
                             ^
TypeError: Cannot read property 'close' of undefined
```

That's what my server.js looks like:
```
var express = require('express');
var createServer = require("auto-sni");


var app = express();

app.get('/', function (req, res) {
       //SOME ACTION
});

createServer({ 
	email: "EMAIL", 
	agreeTos: true,
	debug: true,
	ports: {
        http: 8000, 
        https: 8443
    }
}, app);

```

What am I doing wrong here?

**Comment by DylanPiercey** [comment]
What version of node are you using?

**Comment by brighthero** [comment]
Well, I was using v0.1.12, I'm a little bit ashamed right now... Updated to v4 and I get another error:
```
Subject does not start with '/'.
problems making Certificate Request
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "openssl req -x509 -newkey rsa:2048 -keyout privkey.pem -out cert.pem -days 90 -nodes -subj \'/CN=localhost/emailAddress=EMAIL\' && cat privkey.pem cert.pem | tee -a chain.pem fullchain.pem"' }
Will fall back to self signed certificate.
```
This error gets repeated in an infinite loop.
The `openssl` command is working and openssl is installed.

**Comment by DylanPiercey** [comment]
I haven't tested this on Windows, could you try executing the failed command above without the first "/" before "CN="? If that successfully creates a self signed certificate then I should be able to issue a patch for Windows.

**Comment by brighthero** [comment]
Ok I tested that, the problem seems to be that operators like `&&` don't work in the Windows CMD.

**Comment by DylanPiercey** [comment]
@brighthero Thanks for looking into it. I'll see what I can do sometime this weekend, if you have time a PR would be great.

**Comment by DylanPiercey** [comment]
Going to close this for now since it seems dead in the water and I have opted to avoid supporting windows for now. PR's always welcome though.
